CREATE TABLE usertype (
	usertype_id CHARACTER VARYING(100) NOT NULL,
	usertype CHARACTER VARYING(100) NOT NULL,
	CONSTRAINT PK_USERTYPE_ID PRIMARY KEY (usertype_id)
);

ALTER TABLE usertype OWNER TO postgres;

CREATE TABLE appuser (
	appuser_id CHARACTER VARYING(100) NOT NULL,
	wallet_id CHARACTER VARYING(100),
	password CHARACTER VARYING(100) NOT NULL,
	appuser_usertype_id CHARACTER VARYING(100) NOT NULL,
	CONSTRAINT PK_APPUSER_ID PRIMARY KEY (appuser_id),
	CONSTRAINT FK_USER_TYPE FOREIGN KEY (appuser_usertype_id)
	  REFERENCES usertype (usertype_id) MATCH SIMPLE ON UPDATE RESTRICT ON DELETE RESTRICT
);

ALTER TABLE appuser OWNER TO postgres;